# -*- coding: utf-8 -*-
"""correlation-matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d6EML4llPKb6CtiMkMu_PusglsCuAPaD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/{path to csv file}/correlation-data.csv')

data = data.drop(['Date'], axis=1)
data = data.dropna()

mean_nvidia = data["Nvidia"].mean()
mean_ford = data["Ford"].mean()
mean_shell = data["Shell"].mean()
mean_alpha = data["Alphabet"].mean()

data.corr()

sns.heatmap(data.corr(), annot=True)
plt.show()